# -*- coding: utf-8 -*-
"""firstPlantVision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1siD33LrqvxbY2CjcImeFIPRV66fTYOEr
"""

import tensorflow as tf

gpus = tf.config.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

!pip install opendatasets
import opendatasets as od

od.download("https://www.kaggle.com/datasets/tushar5harma/plant-village-dataset-updated")
#27f6d2df0ad8c76a7f3938189eb1f7c7

#housekeeping
  #os for file stuff, pandas for big math, sklearn for ML stuff
import os
import pandas as pd
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

pfd_folder = "./plant-village-dataset-updated"
image_paths = []
labels = []

#os.listdir(file_path) returns the names of file_path's children
  #only immediate children, and just string names, not addresses
  #both files and folders
for plant_type in os.listdir(pfd_folder):
  #os.path is path-handling module that works across OSs
    #.join() joins the strign arguments, making a file path from separate path segments
    #plant_path: dir for a type of plant
    #plant-path/Training, Testing, Validation
  plant_path = os.path.join(pfd_folder, plant_type)

  for partition in os.listdir(plant_path):
    partition_path = os.path.join(plant_path, partition)

    #I don't think this is doing anything anymore
    #if not os.path.isdir(partition_path):
      #continue


    for label in os.listdir(partition_path):
      label_path = os.path.join(partition_path, label)
      #get the names of folders since they are labels: Healthy, Rust, etc.

      if not os.path.isdir(label_path):
        continue

      for img_file in os.listdir(label_path):
        if img_file.lower().endswith(('jpg', 'jpeg', '.png')):
          #add full path to img_file to image_paths list
            #and label of the image (taken from folder name) to labels list
          image_paths.append(os.path.join(label_path, img_file))
          labels.append(label)

#create dataframe from lists that contain paths to images and their corresponding labels
  #dataframe is pandas datastructure used for associating data with labels
df = pd.DataFrame({
    "image": image_paths,
    "label": labels
})

print(df)

#split 20% of dataframe content into testing data
  #then split 20% of remaining dataframe into validation data
  #stratify arg ensures the ratio of each class to each other is preserved in each subset
train_df, test_df = train_test_split(df, test_size=0.2, stratify=df["label"], random_state=42)
train_df, val_df = train_test_split(train_df, test_size=0.2, stratify=train_df["label"], random_state=42)

#turn the new dataframes into seperate lists of X input images and Y labels
X_train, y_train = train_df["image"].tolist(), train_df["label"].tolist()
X_val, y_val = val_df["image"].tolist(), val_df["label"].tolist()
X_test, y_test = test_df["image"].tolist(), test_df["label"].tolist()

print("Train:", len(X_train), "Validation:", len(X_val), "Test:", len(X_test))
print("Sample:\n\t", X_train[0],"\n\t", y_train[0])

img = mpimg.imread(X_train[0])
plt.imshow(img)
plt.axis("off")
plt.show()

import numpy as np

all_images = X_train + X_val + X_test
shapes=[]
for im in all_images:
  img = mpimg.imread(im)
  shapes.append(img.shape)
avg_shape = np.mean(shapes, axis=0)
print(avg_shape)

print(np.std(shapes))
print(max(shape[0] for shape in shapes), max(shape[1] for shape in shapes), min(shape[0] for shape in shapes), min(shape[1] for shape in shapes))

all_labels = y_train + y_test + y_val
print(len(set(all_labels)))

from tensorflow.keras import datasets, layers, models

cnn = models.Sequential([
    #CNN
    layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu', input_shape=(256,256,3)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(filters=64, kernel_size=(3,3), activation='relu', input_shape=(256,256,3)),
    layers.MaxPooling2D((2,2)),

    #RNN
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(16, activation='softmax')
    #went on autopilot and forgot the outputs are all numbers
      #need to find the number of different labels, and map labels to numbers for one-hot
])

cnn.compile(optimizer='adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'])

from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.preprocessing import LabelEncoder
from PIL import Image

def load_images_from_paths(path_list):
    images = []
    target_size = (256, 256)
    for path in path_list:
        img = Image.open(path).convert("RGB")
        img = img.resize(target_size)
        img_array = np.array(img) / 255.0
        images.append(img_array)
    return np.array(images)

def train_in_batches(cnn, batch_size, Xt, Xv, yte, yve):
  number_of_batches = int(np.ceil( len(Xt)/batch_size ))
  for batch_num in range(number_of_batches):
    start = batch_size*batch_num
    end = start+batch_size

    Xtp_paths = Xt[start:end]
    ytp = yte[start:end]

    Xtp = np.array([load_images_from_paths(img_path) for img_path in Xtp_paths])
    Xvp = np.array([load_images_from_paths(img_path) for img_path in Xv])

    cnn.fit(Xtp, yte, epochs=2, validation_dat=(Xvp, yve))

def test_in_batches(cnn, batch_size, Xt, yte):
  number_of_batches = int(np.ceil( len(Xt)/batch_size ))
  for batch_num in range(number_of_batches):
    start = batch_size*batch_num
    end = start+batch_size

    Xtp_paths = Xt[start:end]
    ytp = yte[start:end]

    Xtp = np.array([load_images_from_paths(img_path) for img_path in Xtp_paths])

    cnn.evaluate(Xtp, ytp)

#encode labels as numbers
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_val_encoded = encoder.transform(y_val)
y_test_encoded = encoder.transform(y_test)

train_in_batches(cnn, 10, X_train, X_val, y_train_encoded, y_val_encoded)